etc/apps/usuarios/urls.py
from django.urls import include
from django.urls import path
from apps.usuarios.views import *
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('cotizacion',cotizar,name="cotizar"),
]

etc/etc/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import TemplateView
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base.html'), name='home'),
    path('usuario/', include(('apps.usuarios.urls','usuarios'),namespace="usuarios")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

etc/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <style>
    
    .transparent
  { 
   background:rgba(0,0,0.2,0.5);  
  } 

  </style>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}ETC Traducciones{% endblock %}</title>
    <link rel="icon" href="">
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontello-2f186091/css/fontello.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
</head>
<body>


	{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">ETC Traducciones</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">
      <li class="nav-item active"><a href="{% url 'home' %}" class="nav-link" >Home<span class="sr-only">(current)</span></a></li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item active"><a href="{% url 'usuarios:cotizar' %}" class="nav-link" >Cotizar</a></li>
    </ul>
    <ul class="navbar-nav navbar-right">
      <li><a href="#" class="nav-link" >Admin</a></li>
    </ul>
  </div>
</nav>
  


	{% endblock %}


   <div class="container my-4">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
          <div class="row">
            <div class="col-6">
              <h1 class="logo">
                <a href="">
                  {% block titulo %} Servicios {% endblock %}
                </a>
              </h1>
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-body">
              {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
              {% block content %}
              {% endblock %}
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </div>

{% block extrajs %}
{% endblock %}
</body>
</html>